### ISSUE TITLE
反馈一个bug

### ISSUE THREAD

**Issue by loverustfs** [tiyee/aliyun-oss-auto-upload#109]
麻烦问您一下，为什么只有部份文件被上传了。

打开了debug调试模式，运行结果如下：

<img width="593" alt="image" src="https://github.com/user-attachments/assets/e0328129-185e-45c6-9400-e239330e9666">

删除所有文件后，看到结果，上传到oss里面的，只有部份文件：

<img width="690" alt="image" src="https://github.com/user-attachments/assets/7e399517-4f79-4736-af38-f25ca4391872">

```
  # Deploy hexo blog website.
    - name: Run deploy
      uses: tiyee/aliyun-oss-auto-upload@v2.0.0
      with:
        region: oss-cn-beijing
        access-key-id: ${{ secrets.ALICLOUDOSS_KEY_ID }}
        access-key-secret: ${{ secrets.ALICLOUDOSS_KEY_SECRET }}
        bucket: rustfs-blog
        secure: true
        local-folder: public # local folder
        remote-dir: /

```

项目代码：https://github.com/rustfs/blog
